# Generated by Django 3.1.4 on 2020-12-12 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created_time',)},
        ),
    ]
