# Generated by Django 3.1.4 on 2020-12-12 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_relation'),
        ('post', '0002_auto_20201212_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile'),
        ),
    ]
