# Generated by Django 3.1.4 on 2020-12-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_retweeted',
            field=models.BooleanField(default=False),
        ),
    ]
