# Generated by Django 3.1.4 on 2020-12-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_is_retweeted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_retweeted',
        ),
        migrations.AddField(
            model_name='post',
            name='retweeted_from',
            field=models.BooleanField(default=None),
        ),
    ]
