# Generated by Django 3.1.4 on 2020-12-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20201215_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='retweeted_from',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
