# Generated by Django 3.1.4 on 2020-12-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20201215_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_retweeted',
            field=models.BooleanField(default=False),
        ),
    ]
