# Generated by Django 3.1.4 on 2020-12-15 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0009_post_is_retweeted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='retweeted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retweet_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
