# Generated by Django 3.1.4 on 2020-12-16 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='post_id',
        ),
    ]
