# Generated by Django 3.1.4 on 2020-12-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20201216_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=None, upload_to='home/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
