# Generated by Django 3.1.4 on 2020-12-16 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follownotif',
            name='following',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='following_notif', to='account.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='follownotif',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_notif', to=settings.AUTH_USER_MODEL),
        ),
    ]
