# Generated by Django 3.1.4 on 2020-12-16 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_post_retweeted_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0002_auto_20201216_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='follownotif',
            name='is_follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='follownotif',
            name='is_like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='follownotif',
            name='liker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liker_notif', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follownotif',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
        migrations.AlterField(
            model_name='follownotif',
            name='follower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower_notif', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follownotif',
            name='following',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following_notif', to=settings.AUTH_USER_MODEL),
        ),
    ]
