# Generated by Django 3.1.4 on 2020-12-16 08:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0010_post_retweeted_by'),
        ('notification', '0003_auto_20201216_1128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowNotif',
            new_name='Notif',
        ),
    ]
