# Generated by Django 3.1.4 on 2020-12-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_notif_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notif',
            name='is_read2',
            field=models.BooleanField(default=False),
        ),
    ]
