# Generated by Django 3.1.4 on 2020-12-16 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_auto_20201216_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notif',
            name='is_read2',
        ),
    ]
