# Generated by Django 3.1.4 on 2020-12-17 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0008_remove_notif_is_read2'),
    ]

    operations = [
        migrations.AddField(
            model_name='notif',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
            preserve_default=False,
        ),
    ]
